### ISSUE TITLE
Send the changes in singbox to upstream

### ISSUE THREAD

**Issue by nimagp** [hiddify/hiddify-next-core#22]
The singbox upstream project doesn't really accept PRs, but you might be able to get the changes merged, considering the popularity of Hiddify Next.

While Hiddify Next is great, it isn't applicable for all purposes. It doesn't have GUI manual configuration support and obviously isn't usable on headless machines. (Eg. Routers)

Thanks.

**Comment by hiddify-com** [comment]
This is exactly we are looking for.

we want to make a connection between js and core to make it possible this connection. 
in this case we can support ui clients in our app

**Comment by nimagp** [comment]
> This is exactly we are looking for.
> 
> we want to make a connection between js and core to make it possible this connection. 
> in this case we can support ui clients in our app

Pardon me, but what connection?

Also, as far as I understand, that would create considerable decrease in performance.

I think @bepass-org wants to go the WASM route. (is the golang VM stable enough yet?) @markpash, too, was going to maintain an Iran-specific version of singbox. 

Maybe you can try to co-operate? It would be absolutely fantastic to have a working framework (uo0sef's project), in addition to having all singbox-based clients built with Iran-specific patches. (markpash intention)

**Comment by markpash** [comment]
That's already the plan, my fork was a testing ground for me, there's a collaborative fork being worked on.
